import { Component } from '@angular/core';

@Component({
  selector: 'laboratorio-modal',
  templateUrl: './laboratorios-modal.component.html',
  styleUrls: ['./laboratorios-modal.component.css']
})
export class LaboratoriosModalComponent {
  puestos = [
    { name: '1° Puesto', active: false },
    { name: '2° Puesto', active: true },
    { name: '3° Puesto', active: true },
    { name: '4° Puesto', active: false },
    { name: '5° Puesto', active: true },
    { name: '6° Puesto', active: false },
    { name: '7° Puesto', active: true },
    { name: '8° Puesto', active: false },
    { name: '9° Puesto', active: true },
    { name: '10° Puesto', active: true },
    { name: '11° Puesto', active: false },
    { name: '12° Puesto', active: false },
    { name: '13° Puesto', active: false },
    { name: '14° Puesto', active: false },
    { name: '15° Puesto', active: false },
    { name: '16° Puesto', active: false },
    { name: '17° Puesto', active: false },
    { name: '18° Puesto', active: false },
    { name: '19° Puesto', active: false },
    { name: '20° Puesto', active: false },
    { name: '21° Puesto', active: false },
    { name: '22° Puesto', active: false },
    { name: '23° Puesto', active: false },
    { name: '24° Puesto', active: false },
    { name: '25° Puesto', active: false },
    { name: '26° Puesto', active: false },
    { name: '27° Puesto', active: false },
    { name: '28° Puesto', active: false },
    { name: '29° Puesto', active: false },
    { name: '30° Puesto', active: false },
    { name: '30° Puesto', active: false },
    { name: '31° Puesto', active: false },
    { name: '32° Puesto', active: false },
    { name: '33° Puesto', active: false },
    { name: '34° Puesto', active: false },
    { name: '35° Puesto', active: false },
    { name: '36° Puesto', active: false },
    { name: '37° Puesto', active: false },
    { name: '38° Puesto', active: false },
    { name: '39° Puesto', active: false },
    { name: '40° Puesto', active: false },
    { name: '41° Puesto', active: false },
    { name: '42° Puesto', active: false },
    { name: '43° Puesto', active: false },
    { name: '44° Puesto', active: false },
    { name: '45° Puesto', active: false },
    { name: '46° Puesto', active: false },
    { name: '47° Puesto', active: false },
    { name: '48° Puesto', active: false },
    { name: '49° Puesto', active: false },
    { name: '50° Puesto', active: false },
    { name: '51° Puesto', active: false },
    { name: '52° Puesto', active: false },
    { name: '53° Puesto', active: false },
    { name: '54° Puesto', active: false },
    { name: '55° Puesto', active: false },
    { name: '56° Puesto', active: false },
    { name: '57° Puesto', active: false },
    { name: '58° Puesto', active: false },
    { name: '59° Puesto', active: false },
    { name: '60° Puesto', active: false },
    { name: '61° Puesto', active: false },
    { name: '62° Puesto', active: false },
    { name: '63° Puesto', active: false },
    { name: '64° Puesto', active: false },
    { name: '65° Puesto', active: false },
    { name: '66° Puesto', active: false },
    { name: '67° Puesto', active: false },
    { name: '68° Puesto', active: false },
    { name: '69° Puesto', active: false },
    { name: '70° Puesto', active: false },
    { name: '497° Puesto', active: false },
    
  ];
}